name: release
on:
  push:
    branches:
      - main
  pull_request_target:
  workflow_dispatch:

env:
  APP_NAME: puniyu-cli

permissions:
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  release:
    if: "!startsWith(github.head_ref, 'release-please')"
    runs-on: ubuntu-latest
    outputs:
      cli: ${{ steps.release-please.outputs['puniyu_cli--release_created'] }}
      cli_tag_name: ${{ steps.release-please.outputs['puniyu_cli--tag_name'] }}
      node: ${{ steps.release-please.outputs['puniyu_cli_node--release_created'] }}
      node_tag_name: ${{ steps.release-please.outputs['puniyu_cli_node--tag_name'] }}
    steps:
      - name: 获取token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 运行 release-please-action
        id: release-please
        uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
  build:
    needs: release
    uses: ./.github/workflows/build.yaml

  build-node:
    needs: release
    uses: ./.github/workflows/build-node.yaml

  publish-cli:
    runs-on: ubuntu-latest
    needs: [ release, build ]
    if: ${{ needs.release.outputs.cli }}
    steps:
      - name: 获取token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          
      - name: 检出代码
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: 设置 rust
        uses: puniyu/setup-rust@main
        with:
          save-cache: true
          prefix-key: ${{ env.APP_NAME }}

      - name: 上传 crates-io
        run: |
          cargo publish --package puniyu-cli
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_TOKEN }}

      - name: 下载构建产物
        uses: dawidd6/action-download-artifact@ac66b43f0e6a346234dd65d4d0c8fbb31cb316e5 # v11
        with:
          name: ^cargo-puniyu-.*
          name_is_regexp: true
          skip_unpack: true

      - name: 上传Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          files: |
            cargo-puniyu-*
          tag_name: ${{ needs.release.outputs.cli_tag_name }}

  publish-npm:
    runs-on: ubuntu-latest
    needs: [ release, build-node ]
    if: ${{ needs.release.outputs.node }}
    steps:
      - name: 获取token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 下载npm包
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: "npm-package"
          path: puniyu-cli

      - name: 下载构建产物
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          pattern: puniyu-cli-node-*
          path: puniyu-cli/artifacts

      - name: 设置pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 10.24.0

      - name: 发布npm包
        run: |
          pnpm install
          pnpm config set provenance true
          pnpm config set registry https://registry.npmjs.org/
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          pnpm run create-npm-dirs
          pnpm run artifacts
          pnpm publish --access public
        working-directory: puniyu-cli
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 上传Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          files: |
            puniyu-cli/artifacts/puniyu-cli-*/puniyu-cli*.node
          tag_name: ${{ needs.release.outputs.node_tag_name }}

